env:
  node: true
  commonjs: true
  es6: true
extends:
  - prettier
  - airbnb-base
plugins:
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  prettier/prettier: error
  consistent-return: 0
  implicit-arrow-linebreak: 0
  class-methods-use-this: 0
ignorePatterns:
  - '*test.js'
